AccountingApp/urls.py
from django.urls import include, path
from AccountingApp import views

app_name = 'AccountingApp'
urlpatterns = [
    # url('$', views.index, name='index'),
    # path('', views.home, name='home'),

    path('settings/', views.settings, name='settings'),
    path('accounts-types/', views.account_types, name='accounts_types'),
    path('chart-of-accounts/', views.chart_of_accounts, name='chart_of_accounts'),
    path('account/<code>/', views.get_account_by_code, name='get_account_by_code'),
    path('edit-account/<code>/', views.edit_account_by_code, name='edit_account_by_code'),
    path('new-account/', views.chart_of_accounts_new, name='chart_of_accounts_new'),
    path('new-transaction/', views.add_transaction, name='add_transaction'),
    path('all-transactions/', views.all_transactions, name='all_transactions'),
    path('transaction/<transaction_id>)/', views.get_transaction_by_id, name='get_transaction_by_id'),
    path('edit-transaction/<transaction_id>/', views.edit_transaction_by_id, name='edit_transaction_by_id'),
    # url('export/(.*)', views.export_data, name="export"),
    path('export/<atype>/', views.export_data, name="export"),  # working fine
    path('import/', views.import_data, name="import"),
    path('import_sheet/', views.import_sheet, name="import_sheet"),  # working fine
    path('handson_view/', views.handson_table, name="handson_view"),

    #url('user_login/', views.user_login, name='user_login'),
]

AccountingProject/urls.py
# from django.conf.urls import url
# from django.contrib import admin
# from django.conf.urls import include

from django.contrib import admin
from django.urls import include, path
from AccountingApp import views

# python manage.py runserver
# r'^(?i)admin/'
urlpatterns = [
    # path(r'^$', views.home, name='home'),
    # path(r'^(?i)contact-us/', views.contactus, name='contact-us'),
    path('', views.home, name='home'),
    path('contact-us/', views.contactus, name='contact-us'),
    path('accounting/', include('AccountingApp.urls')),
    path('accounts/', include('users_accounts.urls', namespace='users_accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('organizations/', include('organizations.urls', namespace='organizations')),
    path('admin/', admin.site.urls)
]

# urlpatterns = [
#     path(r'^$', views.home, name='home'),
#     path(r'^(?i)contact-us/', views.contactus, name='contact-us'),
#     path(r'^(?i)accounting/', include('AccountingApp.urls')),
#     path(r'^(?i)accounts/', include('users_accounts.urls', namespace='users_accounts')),
#     path(r'^(?i)accounts/', include('django.contrib.auth.urls')),
#     path(r'^(?i)organizations/', include('organizations.urls', namespace='organizations')),
#     path(r'^(?i)admin/', admin.site.urls),
# ]

organizations/urls.py
from django.urls import include, path

from tax.views import TaxCreateView, TaxUpdateView
from . import views
from account_types import views as account_types_views
from chart_of_accounts import views as chart_of_accounts_views
from transactions import views as trans_views
from bill.views import BillView, Bills

app_name = 'organizations'

urlpatterns = [
    path('new/',views.CreateOrganization.as_view(), name='create'),
    path('',views.OrganizationList.as_view(), name='all'),
    path('<pk>', views.OrganizationDetailView.as_view(), name='detail'),
    path('edit/<pk>', views.OrganizationUpdateView.as_view(), name='edit'),
    path('delete/<pk>', views.OrganizationDeleteView.as_view(), name='delete'),


    # handling members
    path('add-member/<org_id>-<usr_id>', views.AddMember.as_view(), name='add-member'),
    path('delete-member/<org_id>-<usr_id>', views.DeleteMember.as_view(), name='delete-member'),

    # handling account types
    path('new-account-type/<org_id>',
        account_types_views.CreateAccountType.as_view(),
        name='create-account-type'),
    # path('delete-account-type/(?P<org_id>\w+)-(?P<acc_typ_code>\w+)$', account_types_views.DeleteAccountType.as_view(), name='delete-account-type'),
    path('edit-account-type/<org_id>-<acc_typ_code>-<pk>', account_types_views.AccountTypeUpdateView.as_view(), name='edit-account-type'),
    path('detail-account-type/<org_id>-<acc_typ_code>-<pk>', account_types_views.AccountTypeDetailView.as_view(), name='detail-account-type'),

    # handling chart of accounts
    path('new-account/<org_id>-<acc_typ_code_id>', chart_of_accounts_views.CreateChartOfAccountView.as_view(), name='create-account'),
    path('edit-account/<org_id>-<acc_typ_code_id>-<pk>', chart_of_accounts_views.UpdateChartOfAccountView.as_view(), name='edit-account'),

    # handling Currencies
    path('add-currency/<org_id>', views.CreateCurrenciesView.as_view(), name='add-currency'),
    path('edit-currency/<org_id>-<pk>', views.UpdateCurrenciesView.as_view(), name='edit-currency'),
    path('delete-currency/<org_id>-<pk>', views.DeleteCurrenciesView.as_view(), name='delete-currency'),

    # handling Exchange rates
    path('override-exchange-rate/<org_id>-<curr_id>-<pk>', views.OverrideOrgExchangeRateView.as_view(), name='override-exchange-rate'),

    # handling Transactions
    path('new-transaction/<org_id>', trans_views.CreateTransactionView.as_view(), name='new-transaction'),
    path('transactions/<org_id>', trans_views.TransactionsList.as_view(), name='transactions'),

    # Invite Users
    path('invite-user/<org_id>', views.InviteUserView.as_view(), name='invite-user'),

    # handling Taxes
    path('new-tax/<org_id>', TaxCreateView.as_view(), name='new-tax'),
    path('edit-tax/<org_id>-<pk>', TaxUpdateView.as_view(), name='edit-tax'),

    # handling Bills
    path('new-bill/<org_id>', BillView.as_view(), name='new-bill'),
    path('bills/<org_id>', Bills.as_view(), name='bills'),


]

users_accounts/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users_accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name="login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),

    path('invitation/signup/<org_id>/<inv_id>/', views.InvitationSignUp.as_view(), name="invitation-signup"),
]

AccountingApp/forms.py
from django import forms
from AccountingApp.models import ContactUs, AccountTypes, ChartOfAccounts,Transactions
from django.contrib.auth.models import User
from AccountingApp import views as AppView
# from django.core import validators


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = '__all__'


class TransactionsForm(forms.ModelForm):
    class Meta:
        model = Transactions
        fields = '__all__'

    def clean(self):
        base_currency = AppView.get_base_currency()
        self.cleaned_data['exchange_rate'] = AppView.get_exchange_rate(self.cleaned_data['currency_id'].currency_id,
                                                                     base_currency)

        base_eqv_amount = self.cleaned_data['exchange_rate'] * self.cleaned_data['amount']

        self.cleaned_data['base_currency_id'].currency_id = base_currency
        self.cleaned_data['base_eqv_amount'] = round(base_eqv_amount,6)

        if not AppView.validate_transaction(self.cleaned_data['dr_account_code'].code,
                                            self.cleaned_data['cr_account_code'].code):
            raise forms.ValidationError("Dr and Cr are Not Balanced!")


class AccountTypesForm(forms.ModelForm):
    class Meta:
        model = AccountTypes
        fields = '__all__'


class ChartOfAccountsForm(forms.ModelForm):
    class Meta:
        model = ChartOfAccounts
        fields = '__all__'


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

AccountingApp/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.template import RequestContext
# from django.core.urlresolvers import reverse

from AccountingApp.models import AccountTypes, ChartOfAccounts, ExchangeRate, Transactions, AccountTypesDrCr, Currencies
from AccountingApp.forms import UserForm, ChartOfAccountsForm, TransactionsForm

from AccountingApp import forms
import django_excel as excel
from django import forms as djangoForms


class UploadFileForm(djangoForms.Form):
    file = djangoForms.FileField()


def get_exchange_rate(from_currency_id,to_currency_id):
    swap = 0
    if from_currency_id != to_currency_id:
        try:
            exchange_rate = ExchangeRate.objects.get(from_currency_id=from_currency_id,to_currency_id=to_currency_id)
        except ExchangeRate.DoesNotExist:
            try:
                exchange_rate = ExchangeRate.objects.get(from_currency_id=to_currency_id, to_currency_id=from_currency_id)
                swap = 1
            except ExchangeRate.DoesNotExist:
                exchange_rate = None

        if exchange_rate is not None:
            rate = exchange_rate.override_rate
            if swap == 0:
                return rate if rate > 0 else exchange_rate.rate
            else:
                return 1/rate if rate > 0 else 1/exchange_rate.rate
        else:
            return 0

    else:
        return 1


@login_required
def account_types(request):
    accountTypes_list = AccountTypes.objects.order_by('code')

    my_dict = {'accountTypes': accountTypes_list}

    return render(request, 'AccountingApp/account_types.html', context=my_dict)


@login_required
def get_account_by_code(request, code):

    account = ChartOfAccounts.objects.filter(code=code)
    my_dict = {'chartOfAccounts': account}

    return render(request, 'AccountingApp/chart_of_accounts_filter.html', context=my_dict)


def cancel(request):
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def edit_account_by_code(request, code):

    account = ChartOfAccounts.objects.get(code=code)
    chartOfAccounts_edit = forms.ChartOfAccountsForm(instance=account)

    if request.method == 'POST':
        chartOfAccounts_edit = forms.ChartOfAccountsForm(request.POST, instance=account)

        if chartOfAccounts_edit.is_valid():
            chartOfAccounts_edit.save(commit=True)
            return redirect('AccountingApp:chart_of_accounts')

    my_dict = {'chartOfAccounts': chartOfAccounts_edit, 'code': code}
    return render(request, 'AccountingApp/chart_of_accounts_edit.html', context=my_dict)


@login_required
def chart_of_accounts(request):
    chartOfAccounts_list = ChartOfAccounts.objects.order_by('type_code')

    my_dict = {'chartOfAccounts': chartOfAccounts_list}

    return render(request, 'AccountingApp/chart_of_accounts_all.html', context=my_dict)


@login_required
def chart_of_accounts_new(request):
    chartOfAccounts_new = forms.ChartOfAccountsForm()

    if request.method == 'POST':
        chartOfAccounts_new = forms.ChartOfAccountsForm(request.POST)

        if chartOfAccounts_new.is_valid():
            chartOfAccounts_new.save(commit=True)
            if 'save_add_another' in request.POST:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:
                return redirect('AccountingApp:chart_of_accounts')

    my_dict = {'chartOfAccounts': chartOfAccounts_new}
    return render(request, 'AccountingApp/chart_of_accounts_new.html', context=my_dict)


def home(request):
    return render(request, 'AccountingApp/home.html')


@login_required
def settings(request):
    return render(request, 'AccountingApp/settings.html')


def contactus(request):
    contact_us = forms.ContactUsForm()

    if request.method == 'POST':

        contact_us = forms.ContactUsForm(request.POST)

        if contact_us.is_valid():
            print("Form Validation Success. Prints in console.")
            contact_us.save(commit=True)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    return render(request, 'AccountingApp/contact_us.html', {'contact_us': contact_us})


@login_required
def add_transaction(request):
    transaction = forms.TransactionsForm()

    if request.method == 'POST':

        transaction = forms.TransactionsForm(request.POST)
        if transaction.is_valid():
            transaction.save(commit=True)
            if 'save_add_another' in request.POST:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:
                return redirect('AccountingApp:all_transactions')

    return render(request, 'AccountingApp/transactions_new.html', {'transaction': transaction})


def get_chart_of_accounts_type_code(account_code):
    return ChartOfAccounts.objects.get(code=account_code).type_code


def get_base_currency():
    return Currencies.objects.get(base_currency=True).currency_id


def validate_transaction(dr_account_code, cr_account_code):
    if dr_account_code != cr_account_code:
        dr_type_code = get_chart_of_accounts_type_code(dr_account_code)
        cr_type_code = get_chart_of_accounts_type_code(cr_account_code)

        dr_sign = AccountTypesDrCr.objects.get(code=dr_type_code, dr_cr=1)
        cr_sign = AccountTypesDrCr.objects.get(code=cr_type_code, dr_cr=2)

        if dr_sign.sign == cr_sign.sign:
            return False
        else:
            return True
    else:
        return False


@login_required
def all_transactions(request):
    transactions = Transactions.objects.order_by('transaction_id')

    my_dict = {'transactions': transactions}

    return render(request, 'AccountingApp/transactions_all.html', context=my_dict)


@login_required
def get_transaction_by_id(request, transaction_id):
    transaction = Transactions.objects.filter(transaction_id=transaction_id)
    my_dict = {'transactions': transaction}

    return render(request, 'AccountingApp/transactions_filter.html', context=my_dict)


@login_required
def edit_transaction_by_id(request, transaction_id):
    transaction = Transactions.objects.get(transaction_id=transaction_id)
    transaction_edit = forms.TransactionsForm(instance=transaction)

    if request.method == 'POST':
        transaction_edit = forms.TransactionsForm(request.POST, instance=transaction)

        if transaction_edit.is_valid():
            transaction_edit.save(commit=True)
            return redirect('AccountingApp:all_transactions')

    my_dict = {'transaction': transaction_edit, 'transaction_id': transaction_id}
    return render(request, 'AccountingApp/transactions_edit.html', context=my_dict)


@login_required
def export_data(request, atype):
    if atype == "sheet":
        return excel.make_response_from_a_table(
            AccountTypes, 'xls', file_name="sheet")
    elif atype == "book":
        return excel.make_response_from_tables(
            [Transactions, ChartOfAccounts], 'xls', file_name="book")
    elif atype == "custom":
        account_type = AccountTypes.objects.get(code=1)
        chart_of_account = ChartOfAccounts.objects.filter(type_code=account_type)
        column_names = ['code', 'name', 'type_code', 'main_code']
        return excel.make_response_from_query_sets(
            chart_of_account,
            column_names,
            'xls',
            file_name="custom"
        )
    else:
        return HttpResponseBadRequest(
            "Bad request. please put one of these " +
            "in your url suffix: sheet, book or custom")


@login_required
def import_sheet(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST,
                              request.FILES)
        if form.is_valid():
            request.FILES['file'].save_to_database(
                name_columns_by_row=0,
                model=AccountTypes,
                mapdict=['code', 'id', 'main_code_id', 'name'])
            return HttpResponse("OK")
        else:
            return HttpResponseBadRequest()
    else:
        form = UploadFileForm()
    return render(
        request,
        'AccountingApp/upload_form.html',
        {'form': form})


@login_required
def import_data(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST,
                              request.FILES)

        def choice_func(row):
            q = AccountTypes.objects.filter(slug=row[0])[0]
            row[0] = q
            return row
        if form.is_valid():
            request.FILES['file'].save_book_to_database(
                models=[AccountTypes, ChartOfAccounts],
                initializers=[None, choice_func],
                mapdicts=[
                    ['code', 'name', 'main_code'],
                    ['code', 'name', 'type_code', 'main_code']]
            )
            return redirect('handson_view')
        else:
            return HttpResponseBadRequest()
    else:
        form = UploadFileForm()
    return render(
        request,
        'AccountingApp/upload_form.html',
        {
            'form': form,
            'title': 'Import excel data into database example',
            'header': 'Please upload sample-data.xls:'
        })


def handson_table(request):
    return excel.make_response_from_tables(
        [AccountTypes, ChartOfAccounts], 'handsontable.html')

templates/AccountingApp/account_types.html
{% extends "AccountingApp/base.html" %}
{% block content %}
    <div class="container">
        <div class="table-responsive">
            {% if accountTypes %}
                <table class="table table-hover">
                    <thead>
                    <th>Code</th>
                    <th>Type Name</th>
                    <th>Main Type</th>
                    </thead>

                    {% for accountType in accountTypes %}
                        <tr>
                            <td>{{ accountType.code }}</td>
                            <td>{{ accountType.name }}</td>
                            <td>{{ accountType.main_code }}</td>
                        </tr>
                    {% endfor %}

                </table>
            {% endif %}
        </div>
    <a class="btn btn-success" href="{% url 'AccountingApp:export' atype='sheet' %}"><span class="glyphicon glyphicon-export"></span> Export </a>
    </div>

{% endblock %}

templates/AccountingApp/base.html
<!DOCTYPE html>
{#{% load staticfiles %}#}
{% load static %}
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sharp Accounting!</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
          type="text/css">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/landing-page.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static "css/accAppStyle.css" %}"/>

    <link href="{% static 'css/default.css' %}" type="text/css" media="screen"/>
    <script type="text/javascript" src="{% static 'js/jquery-1.3.2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>
    {% block extrahead %}{% endblock %}

</head>

<body>
<!-- Navigation -->


<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="{% url 'home' %}" title="Home"><span
            class="glyphicon glyphicon-home"></span> Home</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">

        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}

                <li class="nav-item"><a class="nav-link" href="{% url 'organizations:all' %}"><span
                        class="glyphicon glyphicon-globe"></span>
                    Organizations </a>

                    {% if object.accountType_org_id.count > 0 %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'AccountingApp:accounts_types' %}"><span
                                class="glyphicon glyphicon-th-list"></span>
                            Account Types </a>
                        <li class="nav-item"><a class="nav-link"
                                                href="{% url 'AccountingApp:chart_of_accounts' %}"><span
                                class="glyphicon glyphicon-th"></span>
                            Chart Of Accounts</a>
                        <li class="nav-item"><a class="nav-link" href="{% url 'AccountingApp:all_transactions' %}"><span
                            class="glyphicon glyphicon-list-alt"></span>
                        Transaction</a>

                        <li class="nav-item"><a class="nav-link" href="{% url 'organizations:new-bill' org_id=object.id %}"><span
                            class="glyphicon glyphicon-bitcoin"></span>ill</a>
                    {% endif %}

            {% endif %}
        </ul>

        <ul class="nav navbar-nav navbar-right">

            {# Some logic on what to display for last item#}
            {% if user.is_authenticated %}

                <li class="nav-item"><a class="nav-link" href="{% url 'users_accounts:logout' %}">{{ user }} <span
                        class="glyphicon glyphicon-log-out"></span> Logout </a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'AccountingApp:settings' %}"><span
                        class="glyphicon glyphicon-tasks"></span>
                    Settings</a></li>
                {% if user.is_staff %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}"><span
                            class="glyphicon glyphicon-queen"></span> Admin</a></li>
                {% endif %}
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'users_accounts:login' %}"><span
                        class="glyphicon glyphicon-log-in"></span>
                    Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'users_accounts:signup' %}"><span
                        class="glyphicon glyphicon-user"></span>
                    Signup</a></li>
            {% endif %}
            <li class="nav-item"><a class="nav-link" href="{% url 'contact-us' %}"><span
                    class="glyphicon glyphicon-envelope"></span> Contact Us</a></li>

        </ul>

    </div>

</nav>

<div>
    {% block content %}

    {% endblock %}
</div>


<footer>
    <div class="container">
        <ul class="list-inline">
            <li class="list-inline-item">
                <a href="#">Home</a>
            </li>
            <li class="footer-menu-divider list-inline-item">&sdot;</li>
            <li class="list-inline-item">
                <a href="#about">About</a>
            </li>
            <li class="footer-menu-divider list-inline-item">&sdot;</li>
            <li class="list-inline-item">
                <a href="#services">Services</a>
            </li>
            <li class="footer-menu-divider list-inline-item">&sdot;</li>
            <li class="list-inline-item">
                <a href="#contact">Contact</a>
            </li>
        </ul>
        <p class="copyright text-muted small">Copyright &copy; Your Company 2017. All Rights Reserved</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src={% static 'vendor/jquery/jquery.min.js' %}></script>
<script src={% static 'vendor/popper/popper.min.js' %}></script>
<script src={% static 'vendor/bootstrap/js/bootstrap.min.js' %}></script>

</body>
</html>

templates/AccountingApp/chart_of_accounts_all.html
{% extends "AccountingApp/base.html" %}
{% block content %}
    <div class="container">
        <div class="table-responsive">
            {% if chartOfAccounts %}
                <table class="table table-hover">
                    <thead>
                    <th> Edit </th>
                    <th> Code </th>
                    <th> Account Name </th>
                    <th> Type Of Account </th>
                    <th> Main Account </th>
                    </thead>

                    {% for chartOfAccount in chartOfAccounts %}
                        <tr>
                            <td> <a href="{% url 'AccountingApp:edit_account_by_code' code=chartOfAccount.code%}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                            <td> {{ chartOfAccount.code }} </td>
                            <td> {{ chartOfAccount.name }} </td>
                            <td> {{ chartOfAccount.type_code }} </td>
                            <td> {{ chartOfAccount.main_code }} </td>
                        </tr>

                    {% endfor %}

                </table>
            {% endif %}
        </div>
    <a class="btn btn-success" href="{% url 'AccountingApp:chart_of_accounts_new' %}"><span class="glyphicon glyphicon-plus"></span> Create new</a>
    </div>

{% endblock %}

templates/AccountingApp/chart_of_accounts_edit.html
{% extends "AccountingApp/base.html" %}
{% block content %}
    <div>
        <div class="container">
            <form method="POST">

                <table>
                {{ chartOfAccounts.as_table }}
                </table>
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Update">
                <a class="btn btn-default" href="{% url 'AccountingApp:chart_of_accounts'%}"> Cancel</a>

            </form>
        </div>
    </div>
{% endblock %}

templates/AccountingApp/chart_of_accounts_filter.html
{% extends "AccountingApp/base.html" %}
{% block content %}
    <div class="container">
        <div class="table-responsive">
            {% if chartOfAccounts %}
                <table class="table table-hover">
                    <thead>
                    <th> Code </th>
                    <th> Account Name </th>
                    <th> Type Of Account </th>
                    <th> Main Account </th>
                    </thead>

                    {% for chartOfAccount in chartOfAccounts %}
                        <tr>
                            <td> {{ chartOfAccount.code }} </td>
                            <td> {{ chartOfAccount.name }} </td>
                            <td> {{ chartOfAccount.type_code }} </td>
                            <td> {{ chartOfAccount.main_code }} </td>

                        </tr>

                    <tfoot>
                       <tr>
                          <td valign="bottom" align="right">
                              <a class="btn btn-default" href="{% url 'AccountingApp:edit_account_by_code' code=chartOfAccount.code%}" role="button"> Edit </a>
                          </td>
                       </tr>
                    </tfoot>

                    {% endfor %}

                </table>

            {% endif %}
        </div>


    </div>

{% endblock %}

templates/AccountingApp/contact_us.html
{% extends "AccountingApp/base.html" %}
{% block content %}
    <div>
        <div class="container">
            <h1>Contact US!</h1>
            <form method="POST">

                <table>
                {{ contact_us.as_table }}
                </table>
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Submit">

            </form>
        </div>
    </div>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}

                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                    {{ message }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}

{% endblock %}

templates/AccountingApp/settings.html
{% extends "AccountingApp/base.html" %}
{% block content %}
    <p>hi settings!</p>
{% endblock %}

templates/AccountingApp/transactions_filter.html
{% extends "AccountingApp/base.html" %}
{% block content %}
    <div class="container">
        <div class="table-responsive">
            {% if transactions %}
                <table class="table table-hover">
                    <thead>
                    <th> Edit </th>
                    <th> ID </th>
                    <th> Transaction Date </th>
                    <th> Amount </th>
                    <th> Currency </th>
                    <th> Eqv Amount </th>
                    <th> Dr Account </th>
                    <th> Cr Account </th>
                    </thead>

                    {% for transaction in transactions %}
                        <tr>
                        <td> <a href="{% url 'AccountingApp:edit_transaction_by_id' transaction_id=transaction.transaction_id%}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                            <td> {{ transaction.transaction_id }} </td>
                            <td> {{ transaction.transaction_date }} </td>
                            <td> {{ transaction.amount }} </td>
                            <td> {{ transaction.currency_id }} </td>
                            <td> {{ transaction.base_eqv_amount }} </td>
                            <td> {{ transaction.dr_account_code }} </td>
                            <td> {{ transaction.cr_account_code }} </td>

                        </tr>

                    {% endfor %}

                </table>

            {% endif %}
        </div>


    </div>

{% endblock %}